[project]
name = "ocr-cnh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.16",
    "boto3-stubs[textract]>=1.37.16",
]
